<?php

namespace Database\Seeders;

use App\Models\PROFORMA\Fornitore;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $branches = [
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'founded_at' => '2025-01-01',
                'name' => 'Sede di Napoli',
                'address' => 'Via Ferrante Imparato',
                'street_number' => '190',
                'city' => 'Napoli',
                'zip_code' => '80146',
                'province' => 'Napoli',
                'region' => 'Campania',
                'is_main_office' => 1,
                'manager_first_name' => 'SERGIO',
                'manager_last_name' => 'BRACALE',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Taranto',
                'address' => "Via Ettore D'Amore",
                'street_number' => '43/45',
                'city' => 'Taranto',
                'zip_code' => '74121',
                'province' => 'Taranto',
                'region' => 'Puglia',
                'is_main_office' => 0,
                'manager_first_name' => 'MICHELE',
                'manager_last_name' => 'LONGO',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Andria',
                'address' => 'Viale Venezia Giulia',
                'street_number' => '36/36A',
                'city' => 'Andria',
                'zip_code' => '76123',
                'province' => 'Barletta-Andria-Trani',
                'region' => 'Puglia',
                'is_main_office' => 0,
                'manager_first_name' => 'ANTONIO',
                'manager_last_name' => 'POLICASTRO',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Melicucco',
                'address' => 'Via Don Luigi Sturzo',
                'street_number' => '24',
                'city' => 'Melicucco',
                'zip_code' => '89020',
                'province' => 'Reggio Calabria',
                'region' => 'Calabria',
                'is_main_office' => 0,
                'manager_first_name' => 'MICHELE',
                'manager_last_name' => 'ANSELMO',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Foggia',
                'address' => 'Viale Giuseppe La Torre',
                'street_number' => '73',
                'city' => 'Foggia',
                'zip_code' => '71122',
                'province' => 'Foggia',
                'region' => 'Puglia',
                'is_main_office' => 0,
                'manager_first_name' => 'GIORGIO AUDENO',
                'manager_last_name' => 'CAMPANELLA',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Napoli',
                'address' => 'Via Diocleziano',
                'street_number' => '105',
                'city' => 'Napoli',
                'zip_code' => '80124',
                'province' => 'Napoli',
                'region' => 'Campania',
                'is_main_office' => 0,
                'manager_first_name' => 'MAIO CIRO',
                'manager_last_name' => 'DI',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Cesena',
                'address' => 'Via Casadei Secondo',
                'street_number' => '62',
                'city' => 'Cesena',
                'zip_code' => '47522',
                'province' => 'Forlì-Cesena',
                'region' => 'Emilia-Romagna',
                'is_main_office' => 0,
                'manager_first_name' => 'GABRIELE',
                'manager_last_name' => 'FABBRI',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Vibo Valentia',
                'address' => 'Via Piero Gobetti',
                'street_number' => '3',
                'city' => 'Vibo Valentia',
                'zip_code' => '89900',
                'province' => 'Vibo Valentia',
                'region' => 'Calabria',
                'is_main_office' => 0,
                'manager_first_name' => 'ALFONSO',
                'manager_last_name' => "GIOFRE'",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Foggia',
                'address' => 'Via Giuseppe Di Vittorio',
                'street_number' => '64',
                'city' => 'Foggia',
                'zip_code' => '71121',
                'province' => 'Foggia',
                'region' => 'Puglia',
                'is_main_office' => 0,
                'manager_first_name' => 'ANNALISA',
                'manager_last_name' => 'GRANA',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Napoli 2',
                'address' => 'Via Casanova',
                'street_number' => '82',
                'city' => 'Napoli',
                'zip_code' => '80143',
                'province' => 'Napoli',
                'region' => 'Campania',
                'is_main_office' => 0,
                'manager_first_name' => 'GIANLUCA',
                'manager_last_name' => 'GUIDA',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Pescara ',
                'address' => 'Via Tirino',
                'street_number' => '25',
                'city' => 'Pescara',
                'zip_code' => '65126',
                'province' => 'Pescara',
                'region' => 'Abruzzo',
                'is_main_office' => 0,
                'manager_first_name' => 'EMILIA',
                'manager_last_name' => 'INNERO',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Napoli 3',
                'address' => 'Via L. Libroia',
                'street_number' => '8',
                'city' => 'Napoli',
                'zip_code' => '80129',
                'province' => 'Napoli',
                'region' => 'Lazio',
                'is_main_office' => 0,
                'manager_first_name' => 'LUIGI',
                'manager_last_name' => 'MAIELLO',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Foggia',
                'address' => 'Viale Giuseppe Di Vittorio',
                'street_number' => '205',
                'city' => 'Foggia',
                'zip_code' => '71121',
                'province' => 'Foggia',
                'region' => 'Puglia',
                'is_main_office' => 0,
                'manager_first_name' => 'ALESSANDRA',
                'manager_last_name' => 'MARTINO',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Roma',
                'address' => 'Via Dino Penazzato',
                'street_number' => '105',
                'city' => 'Roma',
                'zip_code' => '00179',
                'province' => 'Roma',
                'region' => 'Lazio',
                'is_main_office' => 0,
                'manager_first_name' => 'ANTONIO',
                'manager_last_name' => 'MILANO',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Roma 2',
                'address' => 'Via Cavati',
                'street_number' => '29',
                'city' => 'Roma',
                'zip_code' => '00132',
                'province' => 'Roma',
                'region' => 'Lazio',
                'is_main_office' => 0,
                'manager_first_name' => 'SIMONE',
                'manager_last_name' => 'RENZANI',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Roma 3',
                'address' => 'Via Federico Filippini',
                'street_number' => '283',
                'city' => 'Roma',
                'zip_code' => '00123',
                'province' => 'Roma',
                'region' => 'Lazio',
                'is_main_office' => 0,
                'manager_first_name' => 'PAOLO',
                'manager_last_name' => 'SAJEVA',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Milano',
                'address' => 'Via Pergolesi  Giovanni Battista',
                'street_number' => '9',
                'city' => 'Milano',
                'zip_code' => '20124',
                'province' => 'Milano',
                'region' => 'Lombardia',
                'is_main_office' => 0,
                'manager_first_name' => 'MARIA ANTONIETTA',
                'manager_last_name' => 'SCARPETTI',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Latina',
                'address' => 'Piazzale Granato',
                'street_number' => '25',
                'city' => 'Latina',
                'zip_code' => '04100',
                'province' => 'Latina',
                'region' => 'Lazio',
                'is_main_office' => 0,
                'manager_first_name' => 'ROSARIA',
                'manager_last_name' => 'SENESE',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'company_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'branchable_type' => 'company',
                'branchable_id' => '45d36df8-369f-40ce-b4fd-b5907c342fe9',
                'name' => 'Sede di Grottaminarda',
                'address' => 'Piazza Vittoria',
                'street_number' => '6',
                'city' => 'Grottaminarda',
                'zip_code' => '83035',
                'province' => 'Avellino',
                'region' => 'Campania',
                'is_main_office' => 0,
                'manager_first_name' => 'RINO ANTONIO',
                'manager_last_name' => 'VITALE',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Chunking per evitare problemi di memoria con troppi record inseriti assieme
        foreach ($branches as $branch) {
            $nome = $branch['manager_last_name'] . ' ' . $branch['manager_first_name'];
            $fornitore = Fornitore::where('name', $nome)->first();
            if ($fornitore) {
                $branch['branchable_type'] = 'fornitore';
                $branch['branchable_id'] = $fornitore->id;
            }
            DB::table('branches')->insert($branch);
        }
    }
}
