<?php

namespace Database\Seeders;

use App\Models\DocumentType;
use Illuminate\Database\Seeder;

class DocumentTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $documentTypes = [
            // Documenti personali
            [
                'name' => 'Casellario Giudiziale',
                'slug' => 'casellario-giudiziale',
                'priority' => 1,
                'is_person' => 1,
                'is_signed' => 0,
                'is_monitored' => 1,
                'regex' => '/casellario.*giudiziale|procura.*repubblica/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Carichi Pendenti',
                'slug' => 'carichi-pendenti',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 1,
                'regex' => '/carichi.*pendenti/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Dichiarazione sostitutiva certificato onorabilità',
                'slug' => 'dichiarazione-sostitutiva-certificato-onorabilita',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 1,
                'regex' => '/dichiarazione.*sostitutiva.*certificato.*onorabilit/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Relazione requisiti organizzativi',
                'slug' => 'requisiti-organizzativi',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/requisiti.*organizzativi|art.*6/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Prova Valutativa OAM',
                'description' => 'Evidenza superamento prova valutativa OAM',
                'slug' => 'prova-valutativa-oam',
                'priority' => 1,
                'is_person' => 1,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_agent' => 1,
                'regex' => '/prova.*valutativa.*oam|superamento.*oam/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Attestato OAM',
                'slug' => 'attestato-professionale',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_agent' => 1,
                'is_principal' => 1,
                'regex' => '/attestato.*(oam|ivass)|prova.*valutativa|formazione.*professionale/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Formazione 15h aggiornamento OAM',
                'slug' => 'formazione-15h-aggiornamento-oam',
                'priority' => 1,
                'training_organization' => 'OAM',
                'training_hours' => 15,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 1,
                'is_agent' => 1,
                'is_principal' => 1,
                'regex' => '/attestato.*(oam|ivass)|prova.*valutativa|formazione.*professionale/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Formazione 30h aggiornamento OAM',
                'slug' => 'formazione-30h-aggiornamento-oam',
                'training_hours' => 30,
                'training_organization' => 'OAM',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 1,
                'is_agent' => 1,
                'is_principal' => 1,
                'regex' => '/attestato.*(oam)|prova.*valutativa|formazione.*professionale/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Attestato IVASS',
                'slug' => 'attestato-ivass',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_agent' => 1,
                'is_principal' => 1,
                'regex' => '/attestato.*(ivass)|prova.*valutativa|formazione.*professionale/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Formazione 30h aggiornamento ISVASS',
                'slug' => 'formazione-30h-aggiornamento-isvass',
                'training_hours' => 30,
                'training_organization' => 'ISVASS',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 1,
                'is_agent' => 1,
                'is_principal' => 1,
                'regex' => '/attestato.*(oam|ivass)|prova.*valutativa|formazione.*professionale/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Titolo di Studio',
                'description' => 'Copia del titolo di studio o autocertificazione di possesso',
                'slug' => 'titolo-di-studio',
                'priority' => 1,
                'is_person' => 1,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_agent' => 1,
                'regex' => '/titolo.*studio|diploma|laurea/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Polizza RC Professionale',
                'slug' => 'polizza-rc',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 1,
                'is_agent' => 1,
                'is_principal' => 1,
                'regex' => '/polizza.*rc|responsabilita.*civile|assicurativa/i',
                'created_at' => '2026-03-18 10:18:59',
                'updated_at' => '2026-03-18 10:18:59',
            ],
            [
                'name' => 'Codice Etico',
                'slug' => 'codice-etico',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_company' => 1,
                'regex' => '/modello.*231|codice.*etico/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Regolamento di Trasparenza',
                'slug' => 'trasparenza-avviso',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_company' => 1,
                'regex' => '/regolamento.*trasparenza|principali.*diritti/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Foglio informativo',
                'code' => 'TRASPARENZA',
                'slug' => 'foglio-informativo',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_company' => 1,
                'regex' => '/trasparenza.*sito|foglio.*informativo/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Trasparenza Sito Web',
                'code' => 'TRASPARENZA',
                'slug' => 'trasparenza-web',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_company' => 1,
                'regex' => '/trasparenza.*sito|foglio.*informativo/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Privacy Sito Web',
                'slug' => 'privacy-web',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_company' => 1,
                'regex' => '/privacy.*sito|privacy.*policy/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Modulo AML',
                'slug' => 'modulo-aml',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/verifica.*clientela/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Modulo Privacy',
                'slug' => 'privacy-informativa',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/informativa.*privacy|consenso.*dati/i',
                'created_at' => '2026-03-18 10:18:57',
                'updated_at' => '2026-03-18 10:18:57',
            ],
            [
                'name' => 'Nomina Incaricato',
                'slug' => 'nomina-incaricato',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/nomina.*incaricato/i',
                'created_at' => '2026-03-18 10:18:57',
                'updated_at' => '2026-03-18 10:18:57',
            ],
            [
                'name' => 'Nomina Responsabile',
                'slug' => 'nomina-responsabile',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/nomina.*responsabile/i',
                'created_at' => '2026-03-18 10:18:57',
                'updated_at' => '2026-03-18 10:18:57',
            ],
            [
                'name' => 'Nomina Amministratore di Sistema',
                'slug' => 'nomina-amministratore',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/amministratore.*sistema/i',
                'created_at' => '2026-03-18 10:18:57',
                'updated_at' => '2026-03-18 10:18:57',
            ],
            [
                'name' => 'Procedura Compliance & Risk',
                'slug' => 'proc-compliance-risk',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/compliance.*risk/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Procedura Gestione Reclami',
                'slug' => 'proc-reclami-ricezione',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/ricezione.*trattamento.*reclami/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Informativa Reclami',
                'slug' => 'proc-reclami-info',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/informativa.*risoluzione.*reclami/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Contrato di Mediazione',
                'code' => 'INCARICO-MED',
                'slug' => 'incarico-mediazione',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_company' => 1,
                'regex' => '/lettera.*incarico|contratto.*mediazione/i',
                'created_at' => '2026-03-18 10:18:57',
                'updated_at' => '2026-03-18 10:18:57',
            ],
            [
                'name' => 'Carta di Identità',
                'slug' => 'carta-identita',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/carta.*identit|c\.i\.|identit/i',
                'created_at' => '2026-03-18 10:18:57',
                'updated_at' => '2026-03-18 10:18:57',
            ],
            [
                'name' => 'Patente di Guida',
                'slug' => 'patente',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/patente/i',
                'created_at' => '2026-03-18 10:18:57',
                'updated_at' => '2026-03-18 10:18:57',
            ],
            [
                'name' => 'Procedura Internal Audit',
                'slug' => 'proc-internal-audit',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/internal.*audit/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Procedura AML Verifica',
                'slug' => 'proc-aml-verifica',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/verifica.*clientela/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            [
                'name' => 'Trasparenza TEGM su Web',
                'code' => 'TRASPARENZA',
                'slug' => 'transparency-doc',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'is_company' => 1,
                'regex' => '/rilevazione.*tassi|tassi.*usura|tegm/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],
            // ----------- task document type seeder new ----------
            [
                'name' => 'Modulo esito Audit',
                'slug' => 'modulo-esito-audit',
                'priority' => 1,
                'is_person' => 0,
                'is_signed' => 0,
                'is_monitored' => 0,
                'regex' => '/internal.*audit/i',
                'created_at' => '2026-03-18 10:18:58',
                'updated_at' => '2026-03-18 10:18:58',
            ],

            /*
             * [
             *     'id' => 3,
             *     'name' => 'Passaporto',
             *     'slug' => 'passaporto',
             *     'priority' => 1,
             *     'is_person' => 0,
             *     'is_signed' => 0,
             *     'is_monitored' => 0,
             *     'regex' => '/passaporto/i',
             *     'created_at' => '2026-03-18 10:18:57',
             *     'updated_at' => '2026-03-18 10:18:57',
             * ],
             * [
             *     'id' => 4,
             *     'name' => 'Codice Fiscale / Tessera Sanitaria',
             *     'slug' => 'codice-fiscale',
             *     'priority' => 1,
             *     'is_person' => 0,
             *     'is_signed' => 0,
             *     'is_monitored' => 0,
             *     'regex' => '/codice.*fiscale|tessera.*sanitaria|c\.f\./i',
             *     'created_at' => '2026-03-18 10:18:57',
             *     'updated_at' => '2026-03-18 10:18:57',
             * ],
             *
             * [
             *     'id' => 6,
             *     'name' => 'Consenso Dati Sanitari',
             *     'slug' => 'consenso-sanitario',
             *     'priority' => 1,
             *     'is_person' => 0,
             *     'is_signed' => 0,
             *     'is_monitored' => 0,
             *     'regex' => '/dati.*particolari|sanitari/i',
             *     'created_at' => '2026-03-18 10:18:57',
             *     'updated_at' => '2026-03-18 10:18:57',
             * ],
             *
             * [
             *     'id' => 10,
             *     'name' => 'Questionario AML',
             *     'slug' => 'questionario-aml',
             *     'priority' => 1,
             *     'is_person' => 0,
             *     'is_signed' => 0,
             *     'is_monitored' => 0,
             *     'regex' => '/adeguata.*verifica|questionario.*aml/i',
             *     'created_at' => '2026-03-18 10:18:57',
             *     'updated_at' => '2026-03-18 10:18:57',
             * ],
             * [
             *     'id' => 11,
             *     'name' => 'Titolare Effettivo',
             *     'slug' => 'titolare-effettivo',
             *     'priority' => 1,
             *     'is_person' => 0,
             *     'is_signed' => 0,
             *     'is_monitored' => 0,
             *     'regex' => '/titolare.*effettivo/i',
             *     'created_at' => '2026-03-18 10:18:57',
             *     'updated_at' => '2026-03-18 10:18:57',
             * ],
             * [
             *     'id' => 12,
             *     'name' => 'Dichiarazione PEP',
             *     'slug' => 'dichiarazione-pep',
             *     'priority' => 1,
             *     'is_person' => 0,
             *     'is_signed' => 0,
             *     'is_monitored' => 0,
             *     'regex' => '/persona.*esposta.*politicamente|pep/i',
             *     'created_at' => '2026-03-18 10:18:57',
             *     'updated_at' => '2026-03-18 10:18:57',
             * ],
             *
             *
             *     [
             *         'id' => 18,
             *         'name' => 'Procedura Manuale Operativo',
             *         'slug' => 'proc-manuale-operativo',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/manuale.*operativo/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 19,
             *         'name' => 'Procedura Sistema Deleghe',
             *         'slug' => 'proc-sistema-deleghe',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/sistema.*deleghe/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *
             *     [
             *         'id' => 23,
             *         'name' => 'Procedura AML Profilatura',
             *         'slug' => 'proc-aml-profilatura',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/profilatura.*rischio/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 24,
             *         'name' => 'Procedura AML SOS',
             *         'slug' => 'proc-aml-sos',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/segnalazione.*sospette|sos/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 25,
             *         'name' => 'Procedura Conservazione Dati',
             *         'slug' => 'proc-aml-conservazione',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/conservazione.*dati/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 26,
             *         'name' => 'Procedura Trasparenza Precontrattuale',
             *         'slug' => 'proc-trasparenza-precontrattuale',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/informativa.*precontrattuale/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 27,
             *         'name' => 'Procedura Controllo Pubblicità',
             *         'slug' => 'proc-controllo-pubblicita',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/controllo.*pubblicit/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 30,
             *         'name' => 'Procedura Selezione Rete',
             *         'slug' => 'proc-rete-selezione',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/selezione.*inserimento.*rete/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 31,
             *         'name' => 'Procedura Formazione Rete',
             *         'slug' => 'proc-rete-formazione',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/formazione.*continua/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 32,
             *         'name' => 'Procedura Controlli Rete',
             *         'slug' => 'proc-rete-controlli',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/controlli.*rete/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 33,
             *         'name' => 'Procedura GDPR',
             *         'slug' => 'proc-privacy-gdpr',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/gdpr.*data.*protection/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 34,
             *         'name' => 'Procedura Business Continuity',
             *         'slug' => 'proc-business-continuity',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/business.*continuity|disaster.*recovery/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 36,
             *         'name' => 'Modulo SECCI',
             *         'slug' => 'modulo-secci',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/secci|informazioni.*europee/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 37,
             *         'name' => 'Segnalazione OAM',
             *         'slug' => 'segnalazione-oam',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/segnalazione.*oam/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 38,
             *         'name' => 'Buste Paga',
             *         'slug' => 'buste-paga',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/busta.*paga/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 39,
             *         'name' => 'Certificazione Unica (CU)',
             *         'slug' => 'cu',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/certificazione.*unica|modello.*cu/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 40,
             *         'name' => 'Certificato di Stipendio',
             *         'slug' => 'certificato-stipendio',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/attestato.*servizio|certificato.*stipendio/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 41,
             *         'name' => 'Estratto Conto INPS',
             *         'slug' => 'estratto-inps',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/estratto.*inps|contributivo/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 42,
             *         'name' => 'Cedolino Pensione',
             *         'slug' => 'cedolino-pensione',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/cedolino.*pensione/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 43,
             *         'name' => 'Quota Cedibile',
             *         'slug' => 'quota-cedibile',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/quota.*cedibile/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 44,
             *         'name' => 'Modello OBISM',
             *         'slug' => 'modello-obism',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/obis/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 45,
             *         'name' => 'Conteggio Estintivo',
             *         'slug' => 'conteggio-estintivo',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/conteggio.*estintivo/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *     [
             *         'id' => 46,
             *         'name' => 'Visita Medica',
             *         'slug' => 'visita-medica',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/visita.*medica/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *
             *     [
             *         'id' => 48,
             *         'name' => 'Visura Camerale',
             *         'slug' => 'visura-camerale',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/visura.*camerale|camera.*commercio|registro.*imprese/i',
             *         'created_at' => '2026-03-18 10:18:58',
             *         'updated_at' => '2026-03-18 10:18:58',
             *     ],
             *
             *     [
             *         'id' => 53,
             *         'name' => 'Documento Identità e CF',
             *         'slug' => 'identita-codice-fiscale',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_agent' => 1,
             *         'is_principal' => 1,
             *         'is_client' => 1,
             *         'regex' => '/carta.*identita|passaporto|codice.*fiscale|tessera.*sanitaria/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 54,
             *         'name' => 'Modulo IBAN',
             *         'slug' => 'iban-coordinate',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/iban|coordinate.*bancarie|appoggio.*conto/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 55,
             *         'name' => 'Contratto Collaborazione Firmato',
             *         'slug' => 'contratto-firmato',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/contratto.*collaborazione|scrittura.*privata|accordo.*firmato/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 56,
             *         'name' => 'Autocertificazione Antimafia',
             *         'slug' => 'antimafia',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/antimafia|dichiarazione.*sostitutiva/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 57,
             *         'name' => 'Relazione Interna SOS',
             *         'slug' => 'relazione-sos',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'is_agent' => 1,
             *         'is_principal' => 1,
             *         'regex' => '/relazione.*sos|analisi.*sospetta/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 58,
             *         'name' => 'Ricevuta Portale UIF',
             *         'slug' => 'ricevuta-sos-uif',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'is_agent' => 1,
             *         'is_principal' => 1,
             *         'regex' => '/ricevuta.*uif|infostat.*sos/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 60,
             *         'name' => 'Contratto Collaborazione',
             *         'slug' => 'contratto-agent',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'regex' => '/contratto.*collaborazione|scrittura.*privata/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 61,
             *         'name' => 'Regolamento Privacy',
             *         'code' => 'TRASPARENZA',
             *         'slug' => 'regolamento-privacy',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'regex' => '/privacy|gdpr|regolamento.*privacy/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 64,
             *         'name' => 'Modulo Richiesta Accesso Dati',
             *         'slug' => 'richiesta-accesso-gdpr',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/richiesta.*accesso.*dati|esercizio.*diritti.*privacy/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 65,
             *         'name' => 'Riscontro al Cliente (GDPR)',
             *         'slug' => 'riscontro-accesso-gdpr',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'regex' => '/riscontro.*accesso|invio.*dati.*personali/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 66,
             *         'name' => 'Attestazione Ricevimento Documentazione Informativa',
             *         'description' => 'Attestazione di ricevimento del foglio informativo e altra documentazione di trasparenza',
             *         'slug' => 'attestazione-ricevimento-informativa',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_client' => 1,
             *         'is_practice' => 1,
             *         'regex' => '/attestazione.*ricevimento.*(informativa|documentazione)|ricevuta.*informativa/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 67,
             *         'name' => 'Fattura Pratica Mediazione',
             *         'description' => 'Fatture relative alla pratica di mediazione',
             *         'slug' => 'fattura-pratica-mediazione',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_client' => 1,
             *         'is_practice' => 1,
             *         'regex' => '/fattura.*mediazione|fattura.*n\./i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 68,
             *         'name' => "Comunicazione Compenso all'Istituto",
             *         'description' => "Comunicazione del compenso di mediazione all'Istituto erogante",
             *         'slug' => 'comunicazione-compenso-istituto',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'is_practice' => 1,
             *         'regex' => '/comunicazione.*compenso|compenso.*mediazione/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 69,
             *         'name' => 'Ricevuta Comunicazione Compenso',
             *         'description' => "Attestazione di ricezione della comunicazione del compenso da parte dell'Istituto",
             *         'slug' => 'ricevuta-comunicazione-compenso',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'is_practice' => 1,
             *         'regex' => '/ricezione.*comunicazione.*compenso|attestazione.*compenso/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 70,
             *         'name' => 'Documentazione Servizi Congiunti (Consulenza)',
             *         'description' => 'Documentazione relativa ai servizi offerti al cliente congiuntamente a quello di mediazione',
             *         'slug' => 'documentazione-servizi-congiunti',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_client' => 1,
             *         'is_practice' => 1,
             *         'regex' => '/servizi.*congiunti|contratto.*consulenza/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 71,
             *         'name' => 'Modulo PIES',
             *         'description' => 'Prospetto Informativo Europeo Standardizzato',
             *         'slug' => 'modulo-pies',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_client' => 1,
             *         'is_practice' => 1,
             *         'regex' => '/pies|prospetto.*informativo.*europeo/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 72,
             *         'name' => 'Nota Descrittiva Intermediazione',
             *         'description' => "Nota descrittiva sull'attività di intermediazione svolta dal collaboratore",
             *         'slug' => 'nota-descrittiva-intermediazione',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_agent' => 1,
             *         'is_practice' => 1,
             *         'regex' => '/nota.*descrittiva.*intermediazione|attività.*svolta/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 73,
             *         'name' => 'Curriculum Vitae',
             *         'description' => 'Curriculum vitae et studiorum per avvio mandato',
             *         'slug' => 'curriculum-vitae',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_agent' => 1,
             *         'regex' => '/curriculum.*vitae|cv/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *
             *     [
             *         'id' => 75,
             *         'name' => 'Certificato di Partita IVA',
             *         'description' => 'Certificato di attribuzione Partita IVA',
             *         'slug' => 'certificato-partita-iva',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_agent' => 1,
             *         'regex' => '/partita.*iva|attribuzione.*piva/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 76,
             *         'name' => 'Visura Cariche e Partecipazioni',
             *         'description' => 'Visura camerale cariche e partecipazioni attive',
             *         'slug' => 'visura-cariche-partecipazioni',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'is_agent' => 1,
             *         'regex' => '/visura.*cariche|partecipazioni/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *
             *     [
             *         'id' => 78,
             *         'name' => 'Aggiornamento OAM',
             *         'description' => 'Attestati di aggiornamento professionale OAM successivi',
             *         'slug' => 'aggiornamento-oam',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 1,
             *         'is_agent' => 1,
             *         'regex' => '/aggiornamento.*oam/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 79,
             *         'name' => 'Attestato Antiriciclaggio',
             *         'description' => 'Attestato di formazione antiriciclaggio (se non in OAM)',
             *         'slug' => 'formazione-antiriciclaggio',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 1,
             *         'is_agent' => 1,
             *         'regex' => '/formazione.*antiriciclaggio|attestato.*aml/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 80,
             *         'name' => 'Tassa Concessione IVASS',
             *         'description' => 'Versamento tassa di concessione governativa IVASS',
             *         'slug' => 'tassa-concessione-ivass',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_agent' => 1,
             *         'regex' => '/tassa.*concessione.*ivass|tassa.*governativa/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 81,
             *         'name' => 'Evidenza Iscrizione IVASS',
             *         'description' => 'Evidenza iscrizione al registro IVASS',
             *         'slug' => 'iscrizione-ivass',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_agent' => 1,
             *         'regex' => '/iscrizione.*ivass|registro.*rui/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 82,
             *         'name' => 'Aggiornamento IVASS',
             *         'description' => 'Attestati corso di aggiornamento IVASS successivi',
             *         'slug' => 'aggiornamento-ivass',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 1,
             *         'is_agent' => 1,
             *         'regex' => '/aggiornamento.*ivass/i',
             *         'created_at' => '2026-03-18 10:18:59',
             *         'updated_at' => '2026-03-18 10:18:59',
             *     ],
             *     [
             *         'id' => 83,
             *         'name' => 'Transparency Document',
             *         'code' => 'TRANSPARENCY_DOC',
             *         'codegroup' => 'TRASPARENZA',
             *         'slug' => 'transparency-document',
             *         'priority' => 0,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 1,
             *         'is_company' => 1,
             *         'duration' => 365,
             *         'is_stored' => 1,
             *         'created_at' => '2026-03-22 07:14:23',
             *         'updated_at' => '2026-03-22 07:18:34',
             *     ],
             *     [
             *         'id' => 84,
             *         'name' => 'Regolamento informatico Uso accettabile di PC, account e dati aziendali',
             *         'slug' => 'regolamento-informatico-uso-accettabile',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'regex' => '/regolamento.*informatico|uso.*accettabile|pc.*account.*dati/i',
             *         'created_at' => now(),
             *         'updated_at' => now(),
             *     ],
             *     [
             *         'id' => 85,
             *         'name' => 'Policy smart working Regole per il lavoro agile e la protezione dei dati fuori sede',
             *         'slug' => 'policy-smart-working',
             *         'priority' => 1,
             *         'is_person' => 0,
             *         'is_signed' => 0,
             *         'is_monitored' => 0,
             *         'is_company' => 1,
             *         'regex' => '/policy.*smart.*working|lavoro.*agile|protezione.*dati.*fuori.*sede/i',
             *         'created_at' => now(),
             *         'updated_at' => now(),
             *     ],
             *     [
             *         'id' => 86,
             *         'name' => 'Dichiarazione sostitutiva onorabilità',
             *         'slug' => 'sostitutiva-onorabilita',
             *         'priority' => 1,
             *         'is_person' => 1,
             *         'is_signed' => 0,
             *         'is_monitored' => 1,
             *         'is_company' => 1,
             *         'regex' => '/dichiarazione.*sostitutiva.*onorabilità|onorabilità/i',
             *         'created_at' => now(),
             *         'updated_at' => now(),
             *
             *     ],
             *
             * ]
             */
        ];
        $id = 0;
        // Loop through each document type configuration and store/update inside DB
        foreach ($documentTypes as $type) {
            DocumentType::updateOrCreate(
                ['slug' => $type['slug']],
                $type
            );
        }
    }
}
