<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Clear existing data
        Employee::query()->delete();

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $companyId = '45d36df8-369f-40ce-b4fd-b5907c342fe9';

        // Employee data from SQL, replacing company_id with the first company's ID
        $employeeId = 1;
        $employees = [
            [
                'id' => $employeeId++,
                'company_id' => $companyId,
                'user_id' => null,
                'name' => 'BASTIONE DAVIDE',
                'role_title' => null,
                'cf' => null,
                'email' => 'davide.bastione@races.it',
                'pec' => '',
                'phone' => '06 86768121',
                'department' => null,
                'oam' => null,
                'oam_at' => null,
                'oam_name' => null,
                'numero_iscrizione_rui' => null,
                'ivass' => null,
                'hiring_date' => null,
                'termination_date' => null,
                'branch_id' => null,
                'coordinated_by_id' => null,
                'employee_types' => 'dipendente',
                'supervisor_type' => 'no',
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
                'is_structure' => 0,
                'is_ghost' => 0,
                'oam_dismissed_at' => null,
                'created_at' => '2026-03-20 12:41:45',
                'updated_at' => '2026-03-22 13:07:22',
            ],
            [
                'id' => $employeeId++,
                'company_id' => $companyId,
                'user_id' => null,
                'name' => 'BRACALE SERGIO',
                'role_title' => null,
                'cf' => null,
                'email' => 'sergio.bracale@races.it',
                'pec' => '',
                'phone' => '',
                'department' => null,
                'oam' => null,
                'oam_at' => null,
                'oam_name' => null,
                'numero_iscrizione_rui' => null,
                'ivass' => null,
                'hiring_date' => null,
                'termination_date' => null,
                'branch_id' => null,
                'coordinated_by_id' => null,
                'employee_types' => 'cda',
                'supervisor_type' => 'no',
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
                'is_structure' => 0,
                'is_ghost' => 0,
                'oam_dismissed_at' => null,
                'created_at' => '2026-03-20 12:41:45',
                'updated_at' => '2026-03-22 13:07:22',
            ],
            [
                'id' => $employeeId++,
                'company_id' => $companyId,
                'user_id' => null,
                'name' => 'ALLEGRETTI EUSTACCHIO',
                'role_title' => null,
                'cf' => null,
                'email' => 'eustachio.allegretti@races.it',
                'pec' => '',
                'phone' => '',
                'department' => null,
                'oam' => null,
                'oam_at' => null,
                'oam_name' => null,
                'numero_iscrizione_rui' => null,
                'ivass' => null,
                'hiring_date' => null,
                'termination_date' => null,
                'branch_id' => null,
                'coordinated_by_id' => null,
                'employee_types' => 'cda',
                'supervisor_type' => 'no',
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
                'is_structure' => 0,
                'is_ghost' => 0,
                'oam_dismissed_at' => null,
                'created_at' => '2026-03-20 12:41:45',
                'updated_at' => '2026-03-22 13:07:22',
            ],
            [
                'id' => $employeeId++,
                'company_id' => $companyId,
                'user_id' => null,
                'name' => 'FARAONE VINCENZO',
                'role_title' => null,
                'cf' => null,
                'email' => 'vincenzo.faraone@races.it',
                'pec' => '',
                'phone' => '',
                'department' => null,
                'oam' => null,
                'oam_at' => null,
                'oam_name' => null,
                'numero_iscrizione_rui' => null,
                'ivass' => null,
                'hiring_date' => null,
                'termination_date' => null,
                'branch_id' => null,
                'coordinated_by_id' => null,
                'employee_types' => 'cda',
                'supervisor_type' => 'no',
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
                'is_structure' => 0,
                'is_ghost' => 0,
                'oam_dismissed_at' => null,
                'created_at' => '2026-03-20 12:41:45',
                'updated_at' => '2026-03-22 13:07:22',
            ],
            [
                'id' => $employeeId++,
                'company_id' => $companyId,
                'user_id' => null,
                'name' => 'PICCOLO CARMINE DAVIDE',
                'role_title' => null,
                'cf' => null,
                'email' => 'davide.piccolo@races.it',
                'pec' => '',
                'phone' => '348 3860075',
                'department' => null,
                'oam' => null,
                'oam_at' => null,
                'oam_name' => null,
                'numero_iscrizione_rui' => null,
                'ivass' => null,
                'hiring_date' => null,
                'termination_date' => null,
                'branch_id' => null,
                'coordinated_by_id' => null,
                'employee_types' => 'cda',
                'supervisor_type' => 'no',
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
                'is_structure' => 0,
                'is_ghost' => 0,
                'oam_dismissed_at' => null,
                'created_at' => '2026-03-20 12:41:45',
                'updated_at' => '2026-03-22 13:07:22',
            ],
            [
                'id' => $employeeId++,
                'company_id' => $companyId,
                'user_id' => null,
                'name' => 'MALPELI GERTRUDE',
                'role_title' => null,
                'cf' => null,
                'email' => 'gertrude.malpeli@races.it',
                'pec' => '',
                'phone' => '06 99317742 ',
                'department' => null,
                'oam' => '2023-03-21',
                'oam_at' => '2023-03-21',
                'oam_name' => 'MALPELI GERTRUDE',
                'numero_iscrizione_rui' => 'E000726797',
                'ivass' => null,
                'hiring_date' => null,
                'termination_date' => null,
                'branch_id' => null,
                'coordinated_by_id' => null,
                'employee_types' => 'dipendente',
                'supervisor_type' => 'no',
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
                'is_structure' => 0,
                'is_ghost' => 0,
                'oam_dismissed_at' => null,
                'created_at' => '2026-03-20 12:41:45',
                'updated_at' => '2026-03-22 12:07:36',
            ],
            [
                'id' => $employeeId++,
                'company_id' => $companyId,
                'user_id' => null,
                'name' => 'ZACCARIA  LOREDANA',
                'role_title' => null,
                'cf' => null,
                'email' => 'loredana.zaccaria@races.it',
                'pec' => '',
                'phone' => '339 6781274',
                'department' => null,
                'oam' => null,
                'oam_at' => null,
                'oam_name' => null,
                'numero_iscrizione_rui' => null,
                'ivass' => null,
                'hiring_date' => null,
                'termination_date' => null,
                'branch_id' => null,
                'coordinated_by_id' => null,
                'employee_types' => 'dipendente',
                'supervisor_type' => 'no',
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
                'is_structure' => 0,
                'is_ghost' => 0,
                'oam_dismissed_at' => null,
                'created_at' => '2026-03-20 12:41:45',
                'updated_at' => '2026-03-22 13:07:22',
            ],
        ];

        // Insert employees one by one to handle encryption properly
        $createdCount = 0;
        foreach ($employees as $employeeData) {
            try {
                Employee::create($employeeData);
                $createdCount++;
            } catch (\Exception $e) {
                $this->command->error("Failed to create employee {$employeeData['name']}: " . $e->getMessage());
            }
        }

        if ($createdCount > 0) {
            $this->command->info('Employees seeded successfully!');
            $this->command->info('Total employees created: ' . $createdCount);
            $this->command->info('Using company ID: ' . $companyId);
        }
    }
}
